kind: Service
apiVersion: v1
metadata:
  name: hello-app-service
spec:
  selector:
    app: hello-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080

# Need to run the commands below to expose the deployment
# kubectl expose deployment python-hello-app-deployment --type=LoadBalancer --port=8080
# minikube service python-hello-app-deployment
